PRAGMA foreign_keys = ON;
CREATE TABLE IF NOT EXISTS rides(id TEXT PRIMARY KEY, published TEXT);
CREATE TABLE IF NOT EXISTS revisions(id TEXT PRIMARY KEY, ride TEXT NOT NULL REFERENCES rides(id), manifest TEXT NOT NULL, bytes INTEGER NOT NULL CHECK(bytes>=0), ready INTEGER NOT NULL DEFAULT 0, created INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS assets(key TEXT PRIMARY KEY, revision TEXT NOT NULL REFERENCES revisions(id) ON DELETE CASCADE, sha TEXT NOT NULL, bytes INTEGER NOT NULL, ready INTEGER NOT NULL DEFAULT 0, lease INTEGER NOT NULL DEFAULT 0);
CREATE INDEX IF NOT EXISTS revisions_ride ON revisions(ride);
CREATE TABLE IF NOT EXISTS limits(id INTEGER PRIMARY KEY CHECK(id=1), quota INTEGER NOT NULL);
INSERT OR IGNORE INTO limits VALUES(1,8000000000);
CREATE TRIGGER IF NOT EXISTS enforce_quota BEFORE INSERT ON revisions
WHEN COALESCE((SELECT SUM(bytes) FROM revisions),0)+NEW.bytes > (SELECT quota FROM limits WHERE id=1)
BEGIN SELECT RAISE(ABORT,'Storage quota reached'); END;
