CREATE TABLE IF NOT EXISTS ownership_mods(id TEXT PRIMARY KEY, revision TEXT NOT NULL, document TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS browser_handoffs(hash TEXT PRIMARY KEY, expires INTEGER NOT NULL, owner TEXT NOT NULL, target TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS browser_sessions(hash TEXT PRIMARY KEY, expires INTEGER NOT NULL, owner TEXT NOT NULL);
